// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// i2s //
// --- //

#define i2s_wrap_target 0
#define i2s_wrap 7
#define i2s_pio_version 1

static const uint16_t i2s_program_instructions[] = {
            //     .wrap_target
    0xe03e, //  0: set    x, 30           side 0
    0x8880, //  1: pull   noblock         side 1
    0x6001, //  2: out    pins, 1         side 0
    0x0842, //  3: jmp    x--, 2          side 1
    0xf03e, //  4: set    x, 30           side 2
    0x9880, //  5: pull   noblock         side 3
    0x7001, //  6: out    pins, 1         side 2
    0x1846, //  7: jmp    x--, 6          side 3
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2s_program = {
    .instructions = i2s_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = i2s_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2s_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_wrap_target, offset + i2s_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

