' Stress test SELECT CASE — many CASE clauses (case_end_fixups[32])
DIM x%
x% = 25
SELECT CASE x%
  CASE 1
    PRINT "one"
  CASE 2
    PRINT "two"
  CASE 3
    PRINT "three"
  CASE 4
    PRINT "four"
  CASE 5
    PRINT "five"
  CASE 6
    PRINT "six"
  CASE 7
    PRINT "seven"
  CASE 8
    PRINT "eight"
  CASE 9
    PRINT "nine"
  CASE 10
    PRINT "ten"
  CASE 11
    PRINT "eleven"
  CASE 12
    PRINT "twelve"
  CASE 13
    PRINT "thirteen"
  CASE 14
    PRINT "fourteen"
  CASE 15
    PRINT "fifteen"
  CASE 16
    PRINT "sixteen"
  CASE 17
    PRINT "seventeen"
  CASE 18
    PRINT "eighteen"
  CASE 19
    PRINT "nineteen"
  CASE 20
    PRINT "twenty"
  CASE 21
    PRINT "twenty-one"
  CASE 22
    PRINT "twenty-two"
  CASE 23
    PRINT "twenty-three"
  CASE 24
    PRINT "twenty-four"
  CASE 25
    PRINT "twenty-five"
  CASE 26
    PRINT "twenty-six"
  CASE 27
    PRINT "twenty-seven"
  CASE 28
    PRINT "twenty-eight"
  CASE 29
    PRINT "twenty-nine"
  CASE 30
    PRINT "thirty"
  CASE ELSE
    PRINT "other"
END SELECT
' Test first case
x% = 1
SELECT CASE x%
  CASE 1
    PRINT "first"
  CASE 2
    PRINT "second"
  CASE 3
    PRINT "third"
  CASE 4
    PRINT "fourth"
  CASE 5
    PRINT "fifth"
  CASE 6
    PRINT "sixth"
  CASE 7
    PRINT "seventh"
  CASE 8
    PRINT "eighth"
  CASE 9
    PRINT "ninth"
  CASE 10
    PRINT "tenth"
  CASE 11
    PRINT "eleventh"
  CASE 12
    PRINT "twelfth"
  CASE 13
    PRINT "thirteenth"
  CASE 14
    PRINT "fourteenth"
  CASE 15
    PRINT "fifteenth"
  CASE 16
    PRINT "sixteenth"
  CASE 17
    PRINT "seventeenth"
  CASE 18
    PRINT "eighteenth"
  CASE 19
    PRINT "nineteenth"
  CASE 20
    PRINT "twentieth"
  CASE ELSE
    PRINT "high"
END SELECT
' Test CASE ELSE with many cases
x% = 999
SELECT CASE x%
  CASE 1
    PRINT "a"
  CASE 2
    PRINT "b"
  CASE 3
    PRINT "c"
  CASE 4
    PRINT "d"
  CASE 5
    PRINT "e"
  CASE 6
    PRINT "f"
  CASE 7
    PRINT "g"
  CASE 8
    PRINT "h"
  CASE 9
    PRINT "i"
  CASE 10
    PRINT "j"
  CASE 11
    PRINT "k"
  CASE 12
    PRINT "l"
  CASE 13
    PRINT "m"
  CASE 14
    PRINT "n"
  CASE 15
    PRINT "o"
  CASE 16
    PRINT "p"
  CASE 17
    PRINT "q"
  CASE 18
    PRINT "r"
  CASE 19
    PRINT "s"
  CASE 20
    PRINT "t"
  CASE ELSE
    PRINT "else"
END SELECT
